// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAclkOM8spGrSMXKLzV4e_PO6wLdyIa4mw',
    appId: '1:942082420065:web:54052b00fa0ae7bf86a920',
    messagingSenderId: '942082420065',
    projectId: 'canal-3d713',
    authDomain: 'canal-3d713.firebaseapp.com',
    storageBucket: 'canal-3d713.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_hdUWx8wJPYrq_08Yi9RkXuSsC8YTq5c',
    appId: '1:942082420065:android:2323a7f9e27ba7ef86a920',
    messagingSenderId: '942082420065',
    projectId: 'canal-3d713',
    storageBucket: 'canal-3d713.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA55_1x-9ZJDtEciDbXh9whgvCmnWPm-0o',
    appId: '1:942082420065:ios:515c8cebe16f8f0686a920',
    messagingSenderId: '942082420065',
    projectId: 'canal-3d713',
    storageBucket: 'canal-3d713.appspot.com',
    iosBundleId: 'com.example.canal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA55_1x-9ZJDtEciDbXh9whgvCmnWPm-0o',
    appId: '1:942082420065:ios:efe5c0f39df237c686a920',
    messagingSenderId: '942082420065',
    projectId: 'canal-3d713',
    storageBucket: 'canal-3d713.appspot.com',
    iosBundleId: 'com.example.canal.RunnerTests',
  );
}
